development:
 adapter: mysql2
 database: ruby_getting_started_development
 username: root
 password: root
 host: localhost
 port: ${3306}

test:
 adapter: mysql2
 database: ruby_getting_started_test
 password: root
 port: ${3306}

production:
 adapter: mysql2
 database: ruby_getting_started_production
 username: root
 password: root
 port: ${3306}